### PR TITLE
Add config to fix network

### PR DESCRIPTION
**Pull request by Marsfan**
Added a config to fix the network as suggested by https://github.com/pythops/jetson-nano-image/issues/2#issuecomment-616198027

### CODE REVIEW

**Comment by Marsfan** [comment]
Ok. Seems to not be working right. Will add a commit when I get it working.

**Comment by Marsfan** [comment]
NVM. It is working. I just made a mistake on my end.

**Review by pythops — CHANGES_REQUESTED** [review]
Thanks for your PR.
I prefer using `systemd-resolved` to handle DNS. 
This is a config sample that you can add
```
$ cat  /etc/systemd/resolved.conf

[Resolve]
DNS=1.1.1.1
FallbackDNS=8.8.8.8
#Domains=
LLMNR=no
MulticastDNS=no
DNSSEC=yes
DNSOverTLS=yes
Cache=yes
DNSStubListener=yes
ReadEtcHosts=yes
```

**Comment by Marsfan** [comment]
I will look into this in a few days. I am currently busy working on some other stuff, but I wanted to let you know that I have seen your message.

**Comment by pythops** [comment]
@Marsfan 
I'm closing this PR as I merged another one that contains these changes.

**Comment by Marsfan** [comment]
Sounds good to me. I switched back to using the Nvidia Image because I could not the micro USB serial/network port to work on the Jetson nano when I built my own image.

**Pull request closed without merging**
