### PR TITLE
Missing i2c-tools

### PR DESCRIPTION
**Pull request by mrcmunir**
It's needed for ota installer nvidia-l4t-bootloader package .

### CODE REVIEW

**Comment by pythops** [comment]
Thanks for your contribution. 
I'll take a look later to the ota feature and see if it should be included in this base image or not

**Comment by mrcmunir** [comment]
> Thanks for your contribution. I'll take a look later to the ota feature and see if it should be included in this base image or not

Seems it's needed if you update on L4T repo new flash package nvidia-l4t-bootloader missing this tool cause failed due launch command for it.

**Comment by pythops** [comment]
I did not have that issue when I create an image.
what steps should I follow to see it ?

**Comment by mrcmunir** [comment]
> I did not have that issue when I create an image. what steps should I follow to see it ?

It's when you update nvidia-l4t-bootloader by OTA nvidia ppa on jetson nano.

sudo apt-get update && sudo apt-get upgrade and if new bootloader package .
Said some command i2c not found for flash it.
You can only reproduce the problem if there is a bootloader package to install from apt upgrade.
If you are install BSP deb packages 32.7.2 you will not be able to reproduced it because the python script already installs it fine from the host system.
It is when you do for example latest image 32.7.1 to 32.7.2 or in the future in other new package from nano ubuntu.

**Comment by pythops** [comment]
Thanks for the detailed explanation.
I'm gonna merge it
thanks for your PR :pray:

**Pull request merged**
